apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig-secret
stringData:
  config.json: |
    {
      "auths" : {
        "image-registry.openshift-image-registry.svc.cluster.local:5000" : {
          "auth": "abcdefghijklmn"
        }
      }
    }
